
language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - python setup.py clean build
  - python setup.py test
  - python setup.py install
  - which telegram-interface
  - telegram-interface
